name: 🐛 Found a Bug
description: This template is for reporting broken or incorrect behavior on the processing.org website. (If you have questions about your own code, please visit our forum at discourse.processing.org instead)
body:
- type: dropdown
  id: labels
  attributes:
    label: Select the most appropriate label(s) for this issue.
    description: You may select more than one.
    multiple: true
    options:
      - label: Accessibility
      - label: Books
      - label: Download
      - label: Enhancement
      - label: Examples
      - label: Homepage
      - label: Libraries
      - label: Reference
      - label: Translation
      - label: Tutorials
      - label: Other (specify if possible)
  validations:
    required: false
- type: input
  attributes:
    label: Describe the bug
    description: A clear and concise description of what the bug is.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to reproduce the behavior
    description: Include a simple code snippet that demonstrates the problem, along with any console errors produced. If this isn't possible, then simply describe the issue as best you can.
    value: "### Steps:\n\n1.\n\n2.\n\n3.\n\n### Snippet:\n\n```js\n\n// Paste your code here :)\n\n```\n"
  validations:
    required: true
- type: input
  attributes:
    label: Expected behavior
    description: A clear and concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Screenshots
    description: If applicable, add a screenshot or screen capture to help explain your problem.
  validations:
    required: false
- type: input
  attributes:
    label: Browser version
    description: In the address bar, on Chrome enter "chrome://version", on Firefox enter "about:support". On Safari, use "About Safari".
  validations:
    required: false
- type: input
  attributes:
    label: Operating system
    description: "Ex: Windows/MacOSX/Linux/Android/iOS along with version."
  validations:
    required: false
- type: input
  attributes:
    label: Smartphone details
    description: "Please complete the following information if applicable.\n\n - Device: [e.g. iPhone6]\n - OS: [e.g. iOS8.1]\n - Browser [e.g. stock browser, safari]\n - Version [e.g. 22]"
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional context
    description: Add any other context about the problem here.
  validations:
    required: false
