name: 🚀 Enhancement Proposal
description: This template is for suggesting enhancements or new features for the Processing website.
labels: [enhancement]
body:
- type: dropdown
  id: labels
  attributes:
    label: Which area of the website does this enhancement relate to?
    description: You may select more than one..
    multiple: true
    options:
      - Accessibility
      - Books
      - Download
      - Examples
      - Homepage
      - Libraries
      - Reference
      - Translation
      - Tutorials
      - Other (specify if possible)
- type: textarea
  attributes:
    label: Describe the enhancement
    description: A clear and concise description of what you want to improve or add to the Processing website.
  validations:
    required: true
- type: textarea
  attributes:
    label: Why is this enhancement important?
    description: Explain why this enhancement is necessary or beneficial for the Processing community.
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional context
    description: Add any other context, mockups, or screenshots that help explain the proposal.
  validations:
    required: false
